/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package se_proj;

import java.sql.*;
import java.text.*;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jinzo78
 */
public class AdminForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminForm
     */
    public AdminForm() throws SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException {
        initComponents();
        String date = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
        Globals.getStatement().executeQuery("SELECT * FROM prenotazioni WHERE DataConsegna = \"" + date + "\"");
        Globals.updateRS();
        if (Globals.getResultSet().next())
            jLabel1.setText("<html>Prenotazioni<br><br>Oggi hai delle prenotazioni da chiudere!</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnArticoli = new javax.swing.JButton();
        btnGestioneUtenti = new javax.swing.JButton();
        btnMagazzino = new javax.swing.JButton();
        btnNegozio = new javax.swing.JButton();
        btnPrenotazioni = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnArticoli.setText("Database articoli");
        btnArticoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArticoliActionPerformed(evt);
            }
        });

        btnGestioneUtenti.setText("Gestione utenti");
        btnGestioneUtenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestioneUtentiActionPerformed(evt);
            }
        });

        btnMagazzino.setText("Database magazzino");
        btnMagazzino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMagazzinoActionPerformed(evt);
            }
        });

        btnNegozio.setText("Gestione negozio");
        btnNegozio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNegozioActionPerformed(evt);
            }
        });

        btnPrenotazioni.setText("Gestione prenotazioni");
        btnPrenotazioni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrenotazioniActionPerformed(evt);
            }
        });

        jLabel1.setText("<html>\nPrenotazioni\n<br><br>\nOggi non hai nessuna prenotazione da chiudere.\n</html>");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGestioneUtenti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNegozio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnArticoli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMagazzino)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnPrenotazioni, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGestioneUtenti, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnArticoli, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNegozio, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMagazzino, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPrenotazioni, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestioneUtentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestioneUtentiActionPerformed
        try
        {
            new UserManager(this, true).setVisible(true);
        }
        catch (SQLException|ClassNotFoundException|InstantiationException|IllegalAccessException ex)
        { }
    }//GEN-LAST:event_btnGestioneUtentiActionPerformed

    private void btnArticoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArticoliActionPerformed
        try
        {
            new ArticleManager(this, true).setVisible(true);
        }
        catch (SQLException|ClassNotFoundException|InstantiationException|IllegalAccessException ex)
        { }
    }//GEN-LAST:event_btnArticoliActionPerformed

    private void btnNegozioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNegozioActionPerformed
        try
        {
            new ShopManager(this, true).setVisible(true);
        }
        catch (SQLException|ClassNotFoundException|InstantiationException|IllegalAccessException ex)
        { }
    }//GEN-LAST:event_btnNegozioActionPerformed

    private void btnMagazzinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMagazzinoActionPerformed
        try
        {
            new StockManager(this, true).setVisible(true);
        }
        catch (SQLException|ClassNotFoundException|InstantiationException|IllegalAccessException ex)
        {   try {
            throw ex;
            } catch (SQLException ex1) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex1);
            } catch (ClassNotFoundException ex1) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex1);
            } catch (InstantiationException ex1) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex1);
            } catch (IllegalAccessException ex1) {
                Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex1);
            }
}
    }//GEN-LAST:event_btnMagazzinoActionPerformed

    private void btnPrenotazioniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrenotazioniActionPerformed
        try
        {
            new ReservationsManager(this, true).setVisible(true);
        }
        catch (SQLException|ClassNotFoundException|InstantiationException|IllegalAccessException ex)
        { }
    }//GEN-LAST:event_btnPrenotazioniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try
                {
                    new AdminForm().setVisible(true);
                } catch (SQLException|ClassNotFoundException|InstantiationException|IllegalAccessException e) {JOptionPane.showMessageDialog(null, e.getMessage());}
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArticoli;
    private javax.swing.JButton btnGestioneUtenti;
    private javax.swing.JButton btnMagazzino;
    private javax.swing.JButton btnNegozio;
    private javax.swing.JButton btnPrenotazioni;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
