/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package se_proj;

import javax.swing.JOptionPane;

/**
 *
 * @author jinzo78
 */
public class EditArticle extends javax.swing.JDialog {
    
    private Article searchedArticle;

    public Article getSearchedArticle() {
        return searchedArticle;
    }

    /**
     * Creates new form EditArticle
     */
    public EditArticle(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public EditArticle()
    {
        this(null, true);
    }
    
    public EditArticle(int codice) throws Exception
    {
        this(null, true);
        searchedArticle = new Article("Codice = " + codice);
        txtNome.setText(searchedArticle.getNomeArticolo());
        
        String tipo = searchedArticle.getTipo();
        if (tipo.equals("Console"))
            cmbTipo.setSelectedIndex(0);
        else if (tipo.equals("Accessorio"))
            cmbTipo.setSelectedIndex(1);
        else
            cmbTipo.setSelectedIndex(2);
        
        String console = searchedArticle.getConsole();
        if (console.equals("PC"))
            cmbConsole.setSelectedIndex(0);
        else if (console.equals("PS1"))
            cmbConsole.setSelectedIndex(1);
        else if (console.equals("PS2"))
            cmbConsole.setSelectedIndex(2);
        else if (console.equals("PS3"))
            cmbConsole.setSelectedIndex(3);
        else if (console.equals("PS4"))
            cmbConsole.setSelectedIndex(4);
        else if (console.equals("PSP"))
            cmbConsole.setSelectedIndex(5);
        else if (console.equals("PSVita"))
            cmbConsole.setSelectedIndex(6);
        else if (console.equals("Xbox"))
            cmbConsole.setSelectedIndex(7);
        else if (console.equals("Xbox 360"))
            cmbConsole.setSelectedIndex(8);
        else if (console.equals("Xbox One"))
            cmbConsole.setSelectedIndex(9);
        else if (console.equals("Wii"))
            cmbConsole.setSelectedIndex(10);
        else if (console.equals("WiiU"))
            cmbConsole.setSelectedIndex(11);
        else if (console.equals("NDS"))
            cmbConsole.setSelectedIndex(12);
        else if (console.equals("2DS"))
            cmbConsole.setSelectedIndex(13);
        else if (console.equals("3DS"))
            cmbConsole.setSelectedIndex(14);
        else if (console.equals("GBA"))
            cmbConsole.setSelectedIndex(15);
        else if (console.equals("GameCube"))
            cmbConsole.setSelectedIndex(16);
        else
            cmbConsole.setSelectedIndex(17);
        
        String genere = searchedArticle.getGenere();
        if (genere.isEmpty())
            cmbGenere.setSelectedIndex(0);
        else if (genere.equals("Avventura"))
            cmbGenere.setSelectedIndex(1);
        else if (genere.equals("Azione"))
            cmbGenere.setSelectedIndex(2);
        else if (genere.equals("GdR"))
            cmbGenere.setSelectedIndex(3);
        else if (genere.equals("Simulatore"))
            cmbGenere.setSelectedIndex(4);
        else if (genere.equals("Sport"))
            cmbGenere.setSelectedIndex(5);
        else if (genere.equals("Strategia"))
            cmbGenere.setSelectedIndex(6);
        else if (genere.equals("Indie"))
            cmbGenere.setSelectedIndex(7);
        else
            cmbGenere.setSelectedIndex(7);
        
        txtDescrizione.setText(searchedArticle.getDescrizione());        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmbConsole = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cmbGenere = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescrizione = new javax.swing.JTextArea();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome articolo: ");

        jLabel2.setText("Tipo articolo:");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Console", "Accessorio", "Gioco" }));
        cmbTipo.setSelectedIndex(2);

        jLabel3.setText("Console: ");

        cmbConsole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PC", "PS1", "PS2", "PS3", "PS4", "PSP", "PSVita", "Xbox", "Xbox 360", "Xbox One", "Wii", "WiiU", "NDS", "2DS", "3DS", "GBA", "GameCube", "Altro" }));

        jLabel4.setText("Genere:");

        cmbGenere.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Avventura", "Azione", "GdR", "Simulatore", "Sport", "Strategia", "Indie", "Altro" }));

        jLabel5.setText("Descrizione");

        txtDescrizione.setColumns(20);
        txtDescrizione.setLineWrap(true);
        txtDescrizione.setRows(5);
        jScrollPane1.setViewportView(txtDescrizione);

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbConsole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cmbGenere, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnOK)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cmbConsole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbGenere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOK)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        try
        {
            if (searchedArticle == null)
                searchedArticle = new Article();
            searchedArticle.setNomeArticolo(txtNome.getText());
            searchedArticle.setTipo(cmbTipo.getSelectedItem().toString());
            searchedArticle.setConsole(cmbConsole.getSelectedItem().toString());
            searchedArticle.setGenere(cmbGenere.getSelectedItem().toString().trim());
            searchedArticle.setDescrizione(txtDescrizione.getText());
            searchedArticle.Finalize();
            JOptionPane.showMessageDialog(null, "Operazione completata.");
        } catch (Exception ex) {JOptionPane.showMessageDialog(null, ex.getMessage());}
    }//GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditArticle dialog = new EditArticle(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox cmbConsole;
    private javax.swing.JComboBox cmbGenere;
    private javax.swing.JComboBox cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescrizione;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
