/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package se_proj;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author jinzo78
 */
public class StockManagerForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminForm
     */
    public StockManagerForm() //throws SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException {
    {
        initComponents();
        try
        {
            Globals.getStatement().executeQuery("SELECT articoli.NomeArticolo, articoli.Console, ricevute_magazzino.Quantita, ricevute_magazzino.Data FROM articoli, ricevute_magazzino WHERE articoli.Codice = ricevute_magazzino.Codice;");
            Globals.updateRS();
            String message = "Sono stati trasferiti:\n\n";
            while (Globals.getResultSet().next())
            {
                message += Globals.getResultSet().getString("Quantita") + " copie di \"" + Globals.getResultSet().getString("NomeArticolo") + "\" (" + Globals.getResultSet().getString("Console") + ") giorno " + Globals.getResultSet().getString("Data") + "\n";
            }
            if (message.equals("Sono stati trasferiti:\n\n") == false)
            {
                JOptionPane.showMessageDialog(null, message);
                Globals.getStatement().executeUpdate("DELETE FROM ricevute_magazzino;");
            }
        }
        catch (SQLException/*|ClassNotFoundException|InstantiationException|IllegalAccessException*/ ex) {JOptionPane.showMessageDialog(null, ex.getMessage());}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMagazzino = new javax.swing.JButton();
        btnArticoli = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnMagazzino.setText("Database magazzino");
        btnMagazzino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMagazzinoActionPerformed(evt);
            }
        });

        btnArticoli.setText("Database articoli");
        btnArticoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArticoliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btnArticoli, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMagazzino)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMagazzino, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnArticoli, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMagazzinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMagazzinoActionPerformed
        try
        {
            new StockManager(this, true).setVisible(true);
        }
        catch (SQLException|ClassNotFoundException|InstantiationException|IllegalAccessException ex)
        { }
    }//GEN-LAST:event_btnMagazzinoActionPerformed

    private void btnArticoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArticoliActionPerformed
        try
        {
            new ArticleManager(this, true).setVisible(true);
        }
        catch (java.sql.SQLException|ClassNotFoundException|InstantiationException|IllegalAccessException ex)
        { }
    }//GEN-LAST:event_btnArticoliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockManagerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArticoli;
    private javax.swing.JButton btnMagazzino;
    // End of variables declaration//GEN-END:variables
}
