/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package se_proj;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jinzo78
 */
public class UserManager extends javax.swing.JDialog {

    /**
     * Creates new form UserManager
     */
    public UserManager(java.awt.Frame parent, boolean modal) throws SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException {
        super(parent, modal);
        initComponents();
        loadUsers();
    }

    private void loadUsers() throws SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException 
    {
        Globals.getStatement().executeQuery("SELECT * FROM utenti;");
        Globals.updateRS();
        ((DefaultTableModel)jTable1.getModel()).getDataVector().removeAllElements();
        while (Globals.getResultSet().next())
        {
            ((DefaultTableModel)jTable1.getModel()).addRow(new Object[] {Globals.getResultSet().getString("ID"), Globals.getResultSet().getString("Nome").concat(" " + Globals.getResultSet().getString("Cognome")), Globals.getResultSet().getString("Ruolo")});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnCreaUtente = new javax.swing.JButton();
        btnDatiUtente = new javax.swing.JButton();
        btnDeregistra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome e cognome", "Ruolo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnCreaUtente.setText("Crea utente");
        btnCreaUtente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreaUtenteActionPerformed(evt);
            }
        });

        btnDatiUtente.setText("Dati utente");
        btnDatiUtente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatiUtenteActionPerformed(evt);
            }
        });

        btnDeregistra.setText("Deregistra utente");
        btnDeregistra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeregistraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDatiUtente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreaUtente, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(btnDeregistra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(btnCreaUtente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDatiUtente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeregistra)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreaUtenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreaUtenteActionPerformed
        EditUser editor = new EditUser();
        editor.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent evt)
            {
                try
                {
                    loadUsers();
                } catch (Exception ex) {}
            }
        });
        editor.setVisible(true);
    }//GEN-LAST:event_btnCreaUtenteActionPerformed

    private void btnDatiUtenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatiUtenteActionPerformed
        Object id = jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0);
        try
        {
            new EditUser(Integer.parseInt(id.toString())).setVisible(true);
            loadUsers();
        } catch (Exception ex) {JOptionPane.showMessageDialog(null, ex.getMessage());}
    }//GEN-LAST:event_btnDatiUtenteActionPerformed

    private void btnDeregistraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeregistraActionPerformed
        try
        {
            if (jTable1.getSelectedRow() == -1) return;
            int yesNo = JOptionPane.showConfirmDialog(null, "Sei sicuro di voler deregistrare l'utente?", "Messaggio", JOptionPane.YES_NO_OPTION);
            if (yesNo != JOptionPane.YES_OPTION) return;
            Object id = jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0);
            User user = new User("ID = " + id + ";");
            user.Delete();
            JOptionPane.showMessageDialog(null, "Operazione completata.");
            loadUsers();
        } catch (Exception ex) {JOptionPane.showMessageDialog(null, ex.getMessage());}
    }//GEN-LAST:event_btnDeregistraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try
                {
                    UserManager dialog = new UserManager(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                }
                catch (SQLException|ClassNotFoundException|InstantiationException|IllegalAccessException e) {}
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreaUtente;
    private javax.swing.JButton btnDatiUtente;
    private javax.swing.JButton btnDeregistra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
